import type { ConnectorType } from "./operationsContracts";

export const connectorGuides = [
  {
    id: "csv_excel",
    name: "CSV / Excel",
    category: "文件",
    description: "上传或挂载标准化运营明细文件，适合周期性批量分析。",
    accessMode: "只读",
    availability: "enabled",
    availabilityLabel: "可直接使用",
    authentication: "本地文件无需账号认证",
    requiredFields: ["文件或目录", "字段映射", "数据周期"],
    setupSteps: ["选择数据文件", "确认字段映射", "执行数据校验"],
  },
  {
    id: "mysql",
    name: "MySQL",
    category: "数据库",
    description: "通过只读数据库账号接入订单、商品、渠道和客户数据表。",
    accessMode: "只读",
    availability: "configurable",
    availabilityLabel: "管理员接入",
    authentication: "数据库只读账号",
    requiredFields: ["主机与端口", "数据库名称", "只读用户名", "TLS 方式", "表与字段映射"],
    setupSteps: ["填写连接信息", "验证网络与权限", "选择数据表", "保存字段映射"],
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: "数据库",
    description: "接入 PostgreSQL 业务库或数仓中的运营主题表。",
    accessMode: "只读",
    availability: "configurable",
    availabilityLabel: "管理员接入",
    authentication: "数据库只读账号",
    requiredFields: ["主机与端口", "数据库与 Schema", "只读用户名", "TLS 方式", "表与字段映射"],
    setupSteps: ["填写连接信息", "验证网络与权限", "选择 Schema 与数据表", "保存字段映射"],
  },
  {
    id: "feishu_bitable",
    name: "飞书多维表格",
    category: "协作应用",
    description: "通过飞书开放平台应用读取多维表格中的线索和运营记录。",
    accessMode: "只读",
    availability: "configurable",
    availabilityLabel: "管理员接入",
    authentication: "飞书企业自建应用",
    requiredFields: ["App ID", "App Secret", "多维表格 Token", "数据表 ID", "字段映射"],
    setupSteps: ["创建企业自建应用", "开通只读权限", "填写应用与表格信息", "完成连接验证"],
  },
  {
    id: "feishu_spreadsheet",
    name: "飞书电子表格",
    category: "协作应用",
    description: "读取飞书电子表格中的周期报表和标准化数据区域。",
    accessMode: "只读",
    availability: "configurable",
    availabilityLabel: "管理员接入",
    authentication: "飞书企业自建应用",
    requiredFields: ["App ID", "App Secret", "Spreadsheet Token", "工作表 ID", "读取范围"],
    setupSteps: ["创建企业自建应用", "开通表格只读权限", "填写工作表范围", "完成连接验证"],
  },
  {
    id: "http_api",
    name: "HTTP API",
    category: "接口",
    description: "通过标准 HTTPS 接口读取业务系统提供的结构化数据。",
    accessMode: "只读",
    availability: "configurable",
    availabilityLabel: "管理员接入",
    authentication: "API Key、Bearer Token 或签名认证",
    requiredFields: ["接口地址", "认证方式", "请求参数", "响应字段映射", "分页规则"],
    setupSteps: ["填写接口与认证信息", "发送只读测试请求", "确认响应字段", "保存读取规则"],
  },
  {
    id: "mcp",
    name: "MCP 数据服务",
    category: "Agent 工具",
    description: "通过受控 MCP 工具访问已授权的数据服务和企业应用。",
    accessMode: "只读",
    availability: "configurable",
    availabilityLabel: "管理员接入",
    authentication: "按 MCP 服务端配置",
    requiredFields: ["服务地址", "传输方式", "认证信息", "工具白名单", "数据字段映射"],
    setupSteps: ["登记 MCP 服务", "完成认证", "选择只读工具", "验证返回结构"],
  },
] satisfies ConnectorType[];
